name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main # Triggers on push to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use latest Ubuntu runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u umarsidiki --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t ghcr.io/umarsidiki/fyp:latest --push .

      - name: Trigger Coolify Deploy
        run: |
          curl -X GET "${{ secrets.COOLIFY_WEBHOOK }}" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
